### ISSUE TITLE
Failed to load the autocomplete-js-import package

### ISSUE THREAD

**Issue by wangujianchi** [DanielGarcia-Carrillo/autocomplete-js-import#42]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-js-import](https://github.com/DanielGarcia-Carrillo/autocomplete-js-import) package 1.4.0

### Stack Trace

Failed to load the autocomplete-js-import package

```
At Cannot find module 'fuzzy'

Error: Cannot find module 'fuzzy'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/autocomplete-js-import-master/lib/provider.js:12:17)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/autocomplete-js-import-master/lib/index.js:9:17)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-modules 1.6.7 
atom-beautify 0.29.13 
atom-react-autocomplete 0.1.10 
react-es6-snippets 0.3.0 
atom-react-native-autocomplete 0.0.27 
atom-react-native-autocomplete 0.0.27 
react-snippets 0.7.0 
atom-ternjs 0.16.1 
autocomplete-js-import 1.4.0 
color-picker 2.2.3 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
file-icons 1.7.25 
language-babel 2.55.4 
language-javascript-jsx 0.3.7 
Stylus 3.0.0 
language-vue 0.21.0 
markdown-writer 2.6.2 
minimap 4.26.4 
node-debugger 1.9.1 
pigments 0.38.0 
platformio-ide-terminal 2.2.2 
script 3.12.2 
simplified-chinese-menu 3.5.0 
split-diff 1.1.0 
Stylus 3.0.0 
terminal-panel 1.14.1 
terminal-plus 0.14.5 
```

**Comment by adammenges** [comment]
seeing this as well
